# Generated by Django 2.1.5 on 2021-12-18 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Netfeelex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_film', models.CharField(max_length=200)),
                ('Contenu_film', models.TextField()),
                ('Date_publication', models.DateTimeField(default=datetime.datetime(2021, 12, 18, 13, 37, 23, 537084), verbose_name='Date publié')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='netfeelex', to='core.Category')),
            ],
        ),
    ]
