# Generated by Django 2.1.5 on 2021-12-18 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Netfeelex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_film', models.CharField(max_length=200)),
                ('Contenu_film', models.TextField()),
                ('Date_publication', models.DateTimeField(default=datetime.datetime(2021, 12, 18, 11, 57, 5, 424020), verbose_name='Date publié')),
                ('Category', models.CharField(max_length=200)),
            ],
        ),
    ]
