# Generated by Django 2.1.5 on 2021-12-18 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netfeelex',
            name='Date_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 17, 2, 48, 604203), verbose_name='Date publié'),
        ),
    ]
