# Generated by Django 2.1.5 on 2021-12-18 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211218_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netfeelex',
            name='Date_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 11, 58, 15, 934267), verbose_name='Date publié'),
        ),
    ]
