# Generated by Django 2.1.5 on 2021-12-19 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211218_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netfeelex',
            name='Date_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 5, 0, 50, 340409), verbose_name='Date publié'),
        ),
    ]
